// Writes REPORT.md and returns the exit code (non-zero if any blocker/major check failed).
import fs from 'node:fs';
import path from 'node:path';
import { here } from './lib.mjs';

export function writeReport(rep, partial) {
  const rank = { blocker: 0, major: 1, minor: 2, cosmetic: 3 };
  const failed = rep.checks.filter((c) => !c.ok);
  let manual = [];
  try { manual = JSON.parse(fs.readFileSync(path.join(here, 'manual_defects.json'), 'utf8')); } catch { /* optional */ }
  const serious = failed.filter((c) => rank[c.severity] <= 1).length + manual.filter((d) => rank[d.severity] <= 1 && !d.fixed).length;
  if (partial) return serious ? 1 : 0;

  const L = [];
  L.push('# Visual QA report: sim/dist/index.html');
  L.push('');
  L.push(`Generated by \`node sim/qa/run_qa.mjs\` (wall time ${rep.wallSeconds.toFixed(0)} s). Page under test: \`sim/dist/index.html\`, ${(rep.pageBytes / 1e6).toFixed(2)} MB, opened via \`file://\` in Chromium (headless). Seed 1, fixed scenario inputs, worlds held paused at power-on so scripted runs are deterministic.`);
  L.push('');
  L.push(`Result: **${rep.checks.length - failed.length}/${rep.checks.length} automated checks passed**; ${failed.length} failed; blocker/major defects: **${serious}** (exit code ${serious ? 1 : 0}).`);
  L.push('');
  L.push('## Measurements');
  L.push('');
  for (const [k, v] of Object.entries(rep.numbers)) {
    if (k.startsWith('speed_')) L.push(`- Speed at the 20x setting, ${k.slice(6)}: **${v.ratio.toFixed(1)}x** virtual/wall (${v.virtual_s.toFixed(0)} s virtual in ${v.wall_s.toFixed(1)} s wall, back-to-back Auto grinds; ${v.activeRatio.toFixed(1)}x while a grind was active (${v.activeVirtual.toFixed(0)} s virtual in ${v.activeWall.toFixed(1)} s wall); page read-out min ${v.readoutMin}, median ${v.readoutMedian}).`);
    else L.push(`- ${k}: ${typeof v === 'string' ? v : JSON.stringify(v)}`);
  }
  L.push('');
  L.push('## Defects (automated)');
  L.push('');
  if (!failed.length) L.push('None.');
  else {
    L.push('| Severity | Viewport | Scenario | Check | Detail | Steps to reproduce |');
    L.push('|---|---|---|---|---|---|');
    for (const c of failed.sort((a, b) => rank[a.severity] - rank[b.severity])) {
      L.push(`| ${c.severity} | ${c.vp} | ${c.scn} | ${c.name} | ${c.detail.replace(/\|/g, '/')} | ${(c.repro || '').replace(/\|/g, '/')} |`);
    }
  }
  L.push('');
  L.push('## Defects (manual screenshot review)');
  L.push('');
  if (!manual.length) L.push('None recorded.');
  else {
    L.push('| Severity | Defect | Steps to reproduce |');
    L.push('|---|---|---|');
    for (const d of manual) L.push(`| ${d.severity}${d.fixed ? ' (fixed)' : ''} | ${d.title} | ${d.steps} |`);
  }
  L.push('');
  let review = '';
  try { review = fs.readFileSync(path.join(here, 'visual_review.md'), 'utf8'); } catch { /* optional */ }
  if (review) { L.push('## What the screenshots show (manual review)'); L.push(''); L.push(review.trim()); L.push(''); }

  L.push('## Notes');
  L.push('');
  for (const n of rep.notes) L.push(`- [${n.vp}] ${n.scn}: ${n.text}`);
  L.push('');
  L.push('## All checks');
  L.push('');
  let cur = '';
  for (const c of rep.checks) {
    const k = `${c.vp} / ${c.scn}`;
    if (k !== cur) { cur = k; L.push(''); L.push(`**${k}**`); L.push(''); }
    L.push(`- ${c.ok ? 'PASS' : 'FAIL (' + c.severity + ')'}: ${c.name}${c.detail ? ' (' + c.detail.replace(/\n/g, ' ') + ')' : ''}`);
  }
  L.push('');
  L.push('## Screenshots');
  L.push('');
  L.push('All files are in `sim/qa/out/` (gitignored), named `<viewport>_<scenario>_<what>.png`; a small selection is committed in `sim/qa/screenshots/`.');
  L.push('');
  L.push('```');
  L.push(rep.shots.slice().sort().join('\n'));
  L.push('```');
  fs.writeFileSync(path.join(here, 'REPORT.md'), L.join('\n') + '\n');
  return serious ? 1 : 0;
}
