# Shared source lists and targets for the native and WASM builds of the digital twin.
# Expects SIM_DIR and REPO_DIR to be set by the including CMakeLists.txt.

set(LVGL_DIR "${SIM_DIR}/.deps/lvgl-9.5.0" CACHE PATH "LVGL 9.5.0 source tree (sim/tools/fetch_deps.sh)")
if(NOT EXISTS "${LVGL_DIR}/lvgl.h")
  message(FATAL_ERROR "LVGL not found at ${LVGL_DIR}; run sim/tools/fetch_deps.sh")
endif()

# Firmware sources compiled unmodified. V2-only panel driver and the communication stacks that
# are replaced by stubs (sim/shim/stubs) are excluded; see sim/ARCHITECTURE.md.
file(GLOB_RECURSE TWIN_FW_CPP CONFIGURE_DEPENDS "${REPO_DIR}/src/*.cpp")
file(GLOB TWIN_FW_FONTS CONFIGURE_DEPENDS "${REPO_DIR}/src/font/*.c")
set(TWIN_FW_EXCLUDE_REGEX "/src/(bluetooth/(manager|ota_handler)|network/[a-z_]+)\\.cpp$")
list(FILTER TWIN_FW_CPP EXCLUDE REGEX "${TWIN_FW_EXCLUDE_REGEX}")

file(GLOB TWIN_SHIM_SRC CONFIGURE_DEPENDS "${SIM_DIR}/shim/src/*.cpp")
file(GLOB TWIN_STUB_SRC CONFIGURE_DEPENDS "${SIM_DIR}/shim/stubs/*.cpp")
set(TWIN_CORE_SRC
  "${SIM_DIR}/core/scheduler.cpp"
  "${SIM_DIR}/core/fiber_ucontext.cpp"
  "${SIM_DIR}/core/fiber_emscripten.cpp"
  "${SIM_DIR}/core/world.cpp"
  "${SIM_DIR}/core/runtime.cpp"
  "${SIM_DIR}/core/trace.cpp"
  "${SIM_DIR}/core/operator.cpp"
  "${SIM_DIR}/core/firmware_access.cpp"
)

file(GLOB_RECURSE TWIN_LVGL_SRC CONFIGURE_DEPENDS "${LVGL_DIR}/src/*.c")

set(TWIN_FW_DEFINES
  ARDUINO=10812
  ARDUINO_ARCH_ESP32
  ESP32
  ESP_PLATFORM
  ARDUINO_USB_CDC_ON_BOOT=1
  BOARD_HAS_PSRAM
  LV_LVGL_H_INCLUDE_SIMPLE
  NO_GLOBAL_UPDATE
  FZ_NOHTTPCLIENT
  "LV_CONF_PATH=\"${REPO_DIR}/include/lv_conf.h\""
)

set(TWIN_INCLUDES
  "${REPO_DIR}/components/delta/include"
  "${REPO_DIR}/components/detools/include"
  "${SIM_DIR}/shim/include"
  "${REPO_DIR}/include"
  "${REPO_DIR}/src"
  "${LVGL_DIR}"
  "${LVGL_DIR}/src"
)

# src/config/build_info.h includes the gitignored, build-generated src/config/git_info.h.
if(NOT EXISTS "${REPO_DIR}/src/config/git_info.h")
  file(WRITE "${REPO_DIR}/src/config/git_info.h"
    "#pragma once\n// Generated by the digital twin build (normally tools/build-scripts/pre_build.py)\n"
    "#define GIT_COMMIT_ID \"sim\"\n#define GIT_BRANCH \"sim\"\n#define BUILD_NUMBER 0\n"
    "#define BUILD_TIMESTAMP \"sim\"\n")
endif()

function(twin_add_targets)
  add_library(twin_lvgl STATIC ${TWIN_LVGL_SRC})
  target_compile_definitions(twin_lvgl PUBLIC ${TWIN_FW_DEFINES})
  target_include_directories(twin_lvgl PUBLIC ${TWIN_INCLUDES})
  target_compile_options(twin_lvgl PRIVATE -w)

  if(NOT TARGET simplant)
    add_subdirectory("${SIM_DIR}/plant" "${CMAKE_BINARY_DIR}/plant")
  endif()

  add_library(twin_firmware STATIC ${TWIN_FW_CPP} ${TWIN_FW_FONTS} ${TWIN_SHIM_SRC} ${TWIN_STUB_SRC} ${TWIN_CORE_SRC})
  target_compile_definitions(twin_firmware PUBLIC ${TWIN_FW_DEFINES})
  target_include_directories(twin_firmware PUBLIC ${TWIN_INCLUDES} "${SIM_DIR}")
  target_link_libraries(twin_firmware PUBLIC twin_lvgl simplant m)
  target_compile_options(twin_firmware PRIVATE -Wno-format -Wno-unused-parameter)

  if(NOT EMSCRIPTEN)
    target_sources(twin_firmware PRIVATE "${SIM_DIR}/core/js_api.cpp")
    add_executable(grindsim "${SIM_DIR}/host/grindsim.cpp")
    target_link_libraries(grindsim PRIVATE twin_firmware)
  endif()
endfunction()
